services:
  fomalhaut-app:
    image: fomalhaut-app:vue
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fomalhaut-app
    hostname: fomalhaut-app
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    command: npm run serve -- --port 8080 --host 0.0.0.0

  sensors-log-test-server:
    image: fomalhaut-app:vue
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sensors-log-test-server
    hostname: sensors-log-test-server
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    command: node server.js
