networks:
  fomalhaut-network:
    external: true

services:
  fomalhaut-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fomalhaut-frontend
    hostname: fomalhaut-frontend
    networks:
      - fomalhaut-network
    ports:
      - "20001:20001"
    volumes:
      - ./src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource,operato-windrose-panel
    ports:
      - '3000:3000'
    privileged: true
    volumes:
      - ./grafana-storage:/var/lib/grafana
volumes:
  grafana-storage: {}